#pragma once
enum ASCII {
	NOT_BROKEN = 219,
	BROKEN = 176,
	MISSED = 249,
	HORIZONTAL = 205,
	VERTICAL = 186,
	UPPER_LEFT_CORNER = 201,
	UPPER_RIGHT_CORNER = 187,
	DOWNER_RIGHT_CORNER = 188,
	DOWNER_LEFT_CORNER = 200,
	UPPER_CONNECTOR = 203,
	RIGHT_CONNECTOR = 185,
	LEFT_CONNECTOR = 204,
	DOWNER_CONNECTOR = 202,
	CROSS = 206,
	EMPTY = ' ',
	LITERAL_A = 65
};

enum MENU {
	END_GAME = 3,
	PLAYER_VS_COMPUTER = 1,
	COMPUTER_VS_COMPUTER = 2,
	RANDOM_PLACEMENT = 1,
	DEFOLT_PLACEMENT = 2,
	BREAK = 1,
	END_GAME_MIDDLE_MENU = 2,
	WITHOUT_ALGORITM = 1,
	USE_ALGORITM = 2
};

enum COORDS {

	SHIPS_FIRST_X_PLAYER1 = 3, SHIPS_FIRST_Y_PLAYER1 = 4,
	SHIPS_FIRST_X_PLAYER2 = 53, SHIPS_FIRST_Y_PLAYER2 = 4,

	FIELD_FIRST_XCOORD_PLAYER1 = 5, FIELD_FIRST_YCOORD_PLAYER1 = 3,
	FIELD_SCD_XCOORD_PLAYER1 = 45, FIELD_SCD_YCOORD_PLAYER1 = 23,
	
	FIELD_FIRST_XCOORD_PLAYER2 = FIELD_FIRST_XCOORD_PLAYER1 + 50, FIELD_FIRST_YCOORD_PLAYER2 = FIELD_FIRST_YCOORD_PLAYER1,
	FIELD_SCD_XCOORD_PLAYER2 = FIELD_SCD_XCOORD_PLAYER1 + 50, FIELD_SCD_YCOORD_PLAYER2 = FIELD_SCD_YCOORD_PLAYER1,

	ALPHABED_XCOORD_FST = 7, ALPHABED_YCOORD_FST = 2,
	ALPHABED_XCOORD_SCND = 57, ALPHABED_YCOORD_SCND = 2,

	GAME_RESULT_XCOORD = 40, GAME_RESULT_YCOORD = 10,

	INSCRIPTION_ENEMY_BOARD_COORDX = 54,
	INSCRIPTION_ENEMY_BOARD_COORDY = 0,
	INSCRIPTION_YOUR_BOARD_COORDX = 4,
	INSCRIPTION_YOUR_BOARD_COORDY = 0,
	
	STEP_BY_COORDX = 4,
	STEP_BY_COORDY = 2,

	CELL_NUMBERS_COORDX_FSTPLR = 2,
	CELL_NUMBERS_COORDY_FSTPLR = 4,
	CELL_NUMBERS_COORDX_SCDPLR = 52,
	CELL_NUMBERS_COORDY_SCDPLR = 4,

	MENU_TITLE_FST_COORDX = 7,
	MENU_TITLE_SCD_COORDX = 13,
	MENU_TITLE_COORDY = 35,

	INSCRIPTION_UP_FSTXCOORD = 7,
	INSCRIPTION_UP_SCDXCOORD = 8,

	INSCRIPTION_DOWN_FSTXCOORD = 11,
	INSCRIPTION_DOWN_SCDXCOORD = 16,

	INSCRIPTION_LEFT_FSTXCOORD = 18,
	INSCRIPTION_LEFT_SCDXCOORD = 23,

	INSCRIPTION_RIGHT_FSTXCOORD = 24,
	INSCRIPTION_RIGHT_SCDXCOORD = 30,

	INSCRIPTION_COORDY = 30,

	SHIPS_EXAMPLES_COORDX = 100,
	SHIPS_EXAMPLES_COORDY = 4,
	STEP_BETWEEN_EXSHIPS_COORDY = 4,

	FOUR_DECK_EXAMPLE_FSTCOORDX = 99,
	FOUR_DECK_EXAMPLE_SCDCOORDX = 115,
	FOUR_DECK_EXAMPLE_FSTCOORDY = 4,
	FOUR_DECK_EXAMPLE_SCDCOORDY = 7,
	
	THREE_DECK_EXAMPLE_FSTCOORDX = 99,
	THREE_DECK_EXAMPLE_SCDCOORDX = 112,
	THREE_DECK_EXAMPLE_FSTCOORDY = 8,
	THREE_DECK_EXAMPLE_SCDCOORDY = 11,

	TWO_DECK_EXAMPLE_FSTCOORDX = 99,
	TWO_DECK_EXAMPLE_SCDCOORDX = 108,
	TWO_DECK_EXAMPLE_FSTCOORDY = 12,
	TWO_DECK_EXAMPLE_SCDCOORDY = 15,

	ONE_DECK_EXAMPLE_FSTCOORDX = 99,
	ONE_DECK_EXAMPLE_SCDCOORDX = 104,
	ONE_DECK_EXAMPLE_FSTCOORDY = 16,
	ONE_DECK_EXAMPLE_SCDCOORDY = 19,

	YES = 0,
	NO = 1,

	SPLASH_SCREEN_XCOORD = 10,
	SPLASH_SCREEN_YCOORD = 10
}; 

enum GAME_COUNTERS {
	AMOUNT_OF_CELLS = 10,
	ONE_DECK_FOR_CHOICE = 1,
	TWO_DECK_FOR_CHOICE = 2,
	THREE_DECK_FOR_CHOICE = 3,
	FOUR_DECK_FOR_CHOICE = 4,
	MAX_AMOUNT_OF_DECKS = 20,
	MAX_AMOUNT_OF_SHOTS = 99,
	MAX_AMOUNT_OF_BROKEN = 20
};
